name: CI/CD for HTML Page

on:
  push:
    branches:
      - main  # Change to "master" if your repo uses that

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: html-files
          path: |
            ./*.html  # Ensure all HTML files are uploaded
            ./*.css   # Include CSS files if any

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for deploying to GitHub Pages
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated from v3 to v4
        with:
          name: html-files
          path: ./html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Update if necessary
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's default token
          publish_dir: ./html
